# Header 
site_name: MKDocs Material Template
site_description: MkDocs Material Templates
site_author: Tyson Lee Swetnam
site_url: https://tyson-swetnam.github.io/mkdocs-material-template/

# Footer
repo_name: mkdocs-material-template
repo_url: https://github.com/tyson-swetnam/mkdocs-material-template
edit_uri: edit/main/docs/
# Copyright
copyright: 'Copyright &copy; 2024 Arizona Board of Regents'


# Page tree
nav:
  - Introduction: index.md
  - Logbook: logbook.md
  - Assignments: keysassignments.md
  - KEYS 2024 Main Project: 
    - Poster: poster.md
    - Assignment 1: assignment1.md
    - Assignment 2: assignment2.md
    - Assignment 3: assignment3.md
    - Assignment 4: assignment4.md
    - Assignment 5: assignment5.md
    - Assignment 6: assignment6.md
    - Acknowledgments: acknowledgments.md
    - References: references.md
  - Resources:
    - GitHub: github.md
    - Prompt Engineering: promptengineering.md

# Configuration
theme:
  name: 'material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    scheme: keys
    primary: blue
    accent: orange
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  logo: 'assets/uarizona.png'
  favicon: 'assets/favicon.ico'
# setting features for the navigation tab
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
    - content.code.copy
  # Default values, taken from mkdocs_theme.yml
  language: en
  # custom_dir: 'overrides'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: white)"
      primary: 'white'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
# Options
extra:
  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/[your-githhub-username]
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/[your-twitter-username]
#    - icon: fontawesome/brands/linkedin
#      link: https://www.linkedin.com/in/[your-linkedin-username]
#    - icon: fontawesome/brands/orcid
#      link: https://orcid.org/[your-orcid-id]
# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css
 
plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
